# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='source',
        ),
        migrations.AddField(
            model_name='song',
            name='source_jpg',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='source_mp3',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
