# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-10 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.CharField(max_length=100)),
                ('song_title', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
            ],
        ),
    ]
