// Player
export const SET_CURRENT_SONG = 'SET_CURRENT_SONG';
export const SET_PLAYING = 'SET_PLAYING';
export const SET_NEXT_SONG = 'SET_NEXT_SONG';
export const SET_PREVIOUS_SONG = 'SET_PREVIOUS_SONG';
export const SET_VOLUME = 'SET_VOLUME';
export const SET_TIME = 'SET_TIME';
export const SET_DURATION = 'SET_DURATION';


// Playlist
export const SET_PLAYLIST = 'SET_PLAYLIST';
export const SET_USER_PLAYLISTS = 'SET_USER_PLAYLISTS';
export const SET_ADD_PLAYLIST = 'SET_ADD_PLAYLIST';
export const SET_DELETE_PLAYLIST = 'SET_DELETE_PLAYLIST';
export const SET_ADD_SONG_TO_PLAYLIST = 'SET_ADD_SONG_TO_PLAYLIST';
export const SET_DELETE_SONG_FROM_PLAYLIST = 'SET_DELETE_SONG_FROM_PLAYLIST';


//Admin
export const SET_INFO_FOR_URL = 'SET_INFO_FOR_URL';
export const SET_ADMIN_ADD_SONG = 'SET_ADMIN_ADD_SONG';
export const SET_ADMIN_DELETE_SONG = 'SET_ADMIN_DELETE_SONG';
export const SET_ADMIN_DELETE_ARTIST = 'SET_ADMIN_DELETE_ARTIST';

// Authentication
export const SET_AUTHENTICATION = 'SET_AUTHENTICATION';

